### ISSUE TITLE
Server Profile Naming

### ISSUE THREAD

**Issue by OverlordSock** [Zerrissen/Wintec-IT-Bot#17]
Hello Dev!

An issue we had with the currently running Wintec Discord was users not changing their server profile name to their name so we can identify them. 

Would there be a way to have the Wintec Bot change their server profile as part of the verification process or something similar?

Thank you Dev!

**Comment by Zerrissen** [comment]
I do like the idea of being able to tell others apart.
However, I'm not sure how I feel about *forcing* it upon users.

Perhaps having this prompted instead? Do you think that would suffice?

**Comment by OverlordSock** [comment]
Sounds good! Prompt but not requirement
