### ISSUE TITLE
Students with ID as username cannot verify

### ISSUE THREAD

**Issue by Zerrissen** [Zerrissen/Wintec-IT-Bot#37]
## Issue
The Wintec bot requires students and alumni to verify their status by submitting their student email to receive a verification code.
Current Regular Expression does not allow for students with "old" usernames (their student ID) to be used in the email field. This currently looks for items matching "xxxxxx00". 

## Replication
Submit a valid student email address that has their ID as their username (00000000@student.wintec.ac.nz)
Bot will tell you this is invalid

## Solution
Add numerical student IDs to be used as a student username with regular expression.

**Comment by SkulduggeryDude** [comment]
Added another regex variable for 8 digits, first one being 0 and added it to the if statement
